title: joncrain.github.io
description: >
  [**Jon Crain**](/)  

  [about](/about/)  

  [r&eacute;sum&eacute;](/resume/)
copyright: Jon Crain
sass:
  sass_dir: assets/sass
url: https://joncrain.github.io
disqus_shortname: stratajekylldemo
twitter_username: "niarcnoj"
linkedin_username: "jon-crain"
instagram_username: "joncrain"
pinterest_username:
flickr_username:
github_username:  "joncrain"
feed_icon: rss
email: "joncrain@gmail.com"
plugins: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
google_analytics: UA-91221948-1
remote_theme: joncrain/strata-jekyll